input {
  beats {
    port => 5044
  }
}

filter {
  # UTC 타임스탬프를 KST로 변환
  date {
    match => ["@timestamp", "ISO8601"]
    timezone => "Asia/Seoul"
    target => "@timestamp"
  }

  # 로그 레벨 추출 로직
  grok {
    match => { "message" => [
      "(?<log_level>TRACE|DEBUG|INFO|NOTICE|WARN|WARNING|ERROR|SEVERE|FATAL)[:|\s]",
      "\[(?<log_level>TRACE|DEBUG|INFO|NOTICE|WARN|WARNING|ERROR|SEVERE|FATAL)\]",
      "(level|loglevel|log_level)=(?<log_level>TRACE|DEBUG|INFO|NOTICE|WARN|WARNING|ERROR|SEVERE|FATAL)"
    ]}
    break_on_match => true
    tag_on_failure => ["_grokparsefailure_loglevel"]
  }

  # 로그 레벨이 추출되지 않은 경우 기본값 설정
  if ![log_level] {
    mutate {
      add_field => { "log_level" => "UNKNOWN" }
    }
  }

  # 필요 없는 필드 제거
  mutate {
    remove_field => ["input", "@version", "tags", "log", "[container][labels]", "[container][image]", "[container][id]", "host", "ecs", "agent", "stream"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
}