# 데이터를 Logstash로 수신할 입력을 정의하는 블록
input {
  beats { # Beats로부터 데이터를 수신
    port => 5044  # Logstash가 Beats로부터 로그를 수신할 포트를 지정
  }
}

# 입력된 데이터를 처리하고 필터링하는 블록
filter {
  # 특정 필드만 추출
  mutate {
    remove_field => [ "agent", "host", "ecs", "log.offset", "input", "container.labels", "stream" ]
  }
}

# 필터링된 데이터를 최종 출력할 방식 정의
output {
  elasticsearch { # 데이터를 Elasticsearch로 출력하는 플러그인
    hosts => ["http://elasticsearch:9200"] # 데이터를 전송할 Elasticsearch의 호스트 주소를 지정
    index => "docker-logs-%{+YYYY.MM.dd}" # 데이터를 저장할 Elasticsearch 인덱스를 지정
  }
#  stdout { codec => rubydebug }  # 로그를 콘솔에도 출력 (디버깅용)
}

